name: test

on:
  push:
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download latest Nintendont artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          branch: slippi
          repo: project-slippi/Nintendont
      - name: Zip Release Artifact
        run: |
          mv release*/apps ./
          mv loader*/* ./
          zip -r "Slippi-Nintendont-${{ env.VERSION }}.zip" apps/
          rm -rf release* loader* apps/
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
